language: ruby
cache: bundler

rvm:
  - ruby
  - 2.1.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - zack@ziggidycreative.com
    on_failure: change
    on_success: never